import type { Product } from './types'

const D = {
  shopifyProductId: '',
  image: null,
  variants: [],
} satisfies Partial<Product>

export const MOCK_PRODUCTS: Product[] = [
  {
    ...D,
    id: 'whey-protein',
    handle: 'whey-protein',
    name: 'CHRGD Whey Protein',
    category: 'Protein',
    subcategory: 'Whey',
    price: 34.99,
    description: 'Premium whey isolate, 25g protein per serving, fast-absorbing.',
    safeWording: 'Selected based on your muscle and recovery goals. Commonly used by people with similar training profiles.',
    goalTags: ['muscle', 'recovery', 'bulking'],
    stimulant: false,
    vegan: false,
    beginner: true,
    stackPriority: 10,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-001',
    accentColor: '#cfff32',
  },
  {
    ...D,
    id: 'vegan-protein',
    handle: 'vegan-protein',
    name: 'CHRGD Plant Protein',
    category: 'Protein',
    subcategory: 'Plant-based',
    price: 36.99,
    description: 'Complete plant protein blend, 22g protein per serving.',
    safeWording: 'Selected to suit your dietary preferences. Commonly used by plant-based athletes with similar goals.',
    goalTags: ['muscle', 'recovery', 'health', 'bulking'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 10,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-002',
    accentColor: '#86efac',
  },
  {
    ...D,
    id: 'creatine-mono',
    handle: 'creatine-mono',
    name: 'CHRGD Creatine Monohydrate',
    category: 'Performance',
    subcategory: 'Creatine',
    price: 19.99,
    description: 'Micronised creatine monohydrate, 5g per serving.',
    safeWording: 'One of the most researched supplements in sport science. Selected based on your performance and strength goals.',
    goalTags: ['muscle', 'performance', 'bulking', 'energy'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 9,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-003',
    accentColor: '#cfff32',
  },
  {
    ...D,
    id: 'pre-workout-standard',
    handle: 'pre-workout-standard',
    name: 'CHRGD Pre-Workout',
    category: 'Pre-Workout',
    subcategory: 'Standard',
    price: 29.99,
    description: 'Moderate-stim pre-workout with beta-alanine, caffeine and L-citrulline.',
    safeWording: 'Selected to suit your training style. Commonly used by people with your energy and performance goals.',
    goalTags: ['energy', 'performance', 'muscle'],
    stimulant: true,
    vegan: true,
    beginner: false,
    stackPriority: 8,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-004',
    accentColor: '#f97316',
  },
  {
    ...D,
    id: 'pre-workout-stim-free',
    handle: 'pre-workout-stim-free',
    name: 'CHRGD Stim-Free Pre',
    category: 'Pre-Workout',
    subcategory: 'Stim-free',
    price: 27.99,
    description: 'Caffeine-free pump formula with L-citrulline, betaine and nitrates.',
    safeWording: 'Selected to match your caffeine preference. Supports blood flow and training sessions without added stimulants.',
    goalTags: ['energy', 'performance'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 7,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-005',
    accentColor: '#38bdf8',
  },
  {
    ...D,
    id: 'bcaa',
    handle: 'bcaa',
    name: 'CHRGD BCAA + Hydration',
    category: 'Amino Acids',
    subcategory: 'BCAA',
    price: 24.99,
    description: '2:1:1 BCAA ratio with added electrolytes for hydration.',
    safeWording: 'Selected to support your recovery and hydration goals. Commonly used by athletes with similar training frequency.',
    goalTags: ['recovery', 'hydration', 'performance'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 6,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-006',
    accentColor: '#818cf8',
  },
  {
    ...D,
    id: 'electrolytes',
    handle: 'electrolytes',
    name: 'CHRGD Electrolyte Mix',
    category: 'Hydration',
    subcategory: 'Electrolytes',
    price: 17.99,
    description: 'Sodium, potassium and magnesium blend for optimal hydration.',
    safeWording: 'Selected to match your hydration goals and training frequency. Commonly used by endurance and high-frequency athletes.',
    goalTags: ['hydration', 'performance', 'recovery'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 7,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-007',
    accentColor: '#38bdf8',
  },
  {
    ...D,
    id: 'omega3',
    handle: 'omega3',
    name: 'CHRGD Omega-3',
    category: 'Health',
    subcategory: 'Essential Fats',
    price: 14.99,
    description: 'High-strength fish oil, 1000mg EPA+DHA per serving.',
    safeWording: 'Selected to support your general health goals. Omega-3s are commonly used by athletes as part of an active lifestyle routine.',
    goalTags: ['health', 'recovery'],
    stimulant: false,
    vegan: false,
    beginner: true,
    stackPriority: 6,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-008',
    accentColor: '#fbbf24',
  },
  {
    ...D,
    id: 'vitamin-d3-k2',
    handle: 'vitamin-d3-k2',
    name: 'CHRGD Vitamin D3+K2',
    category: 'Health',
    subcategory: 'Vitamins',
    price: 12.99,
    description: 'D3 3000IU with K2 MK-7 for optimal absorption and bone support.',
    safeWording: 'Selected to support your general health routine. Commonly included in stacks for people with desk-based lifestyles.',
    goalTags: ['health'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 5,
    stackLevels: ['essentials', 'performance', 'complete'],
    shopifyVariantId: 'mock-009',
    accentColor: '#fde68a',
  },
  {
    ...D,
    id: 'magnesium',
    handle: 'magnesium',
    name: 'CHRGD Magnesium Glycinate',
    category: 'Health',
    subcategory: 'Minerals',
    price: 14.99,
    description: 'Highly bioavailable magnesium glycinate, 400mg per serving.',
    safeWording: 'Selected to suit your sleep and recovery goals. Commonly used by people with high training loads and busy lifestyles.',
    goalTags: ['recovery', 'health'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 5,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-010',
    accentColor: '#c4b5fd',
  },
  {
    ...D,
    id: 'fat-burner',
    handle: 'fat-burner',
    name: 'CHRGD Thermo',
    category: 'Body Composition',
    subcategory: 'Thermogenic',
    price: 32.99,
    description: 'Thermogenic blend with green tea extract, L-carnitine and cayenne.',
    safeWording: 'Selected to match your cutting goals. Commonly used by people looking to support their calorie-controlled diet routine.',
    goalTags: ['cutting', 'energy'],
    stimulant: true,
    vegan: true,
    beginner: false,
    stackPriority: 7,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-011',
    accentColor: '#f87171',
  },
  {
    ...D,
    id: 'mass-gainer',
    handle: 'mass-gainer',
    name: 'CHRGD Mass Builder',
    category: 'Protein',
    subcategory: 'Mass Gainer',
    price: 42.99,
    description: '600kcal mass gainer with 45g protein and complex carbs.',
    safeWording: 'Selected to support your bulking goals. Commonly used by hardgainers and athletes in calorie surplus phases.',
    goalTags: ['bulking', 'muscle'],
    stimulant: false,
    vegan: false,
    beginner: false,
    stackPriority: 8,
    stackLevels: ['performance', 'complete'],
    shopifyVariantId: 'mock-012',
    accentColor: '#fb923c',
  },
  {
    ...D,
    id: 'collagen',
    handle: 'collagen',
    name: 'CHRGD Collagen + Vitamin C',
    category: 'Recovery',
    subcategory: 'Joint Support',
    price: 22.99,
    description: 'Type I & III collagen peptides with 200mg Vitamin C for absorption.',
    safeWording: 'Selected to support your recovery goals. Commonly included in stacks for high-frequency athletes and those focused on joint health.',
    goalTags: ['recovery', 'health', 'performance'],
    stimulant: false,
    vegan: false,
    beginner: true,
    stackPriority: 5,
    stackLevels: ['complete'],
    shopifyVariantId: 'mock-013',
    accentColor: '#fdba74',
  },
  {
    ...D,
    id: 'sleep-support',
    handle: 'sleep-support',
    name: 'CHRGD Sleep & Recovery',
    category: 'Recovery',
    subcategory: 'Sleep',
    price: 19.99,
    description: 'Magnesium, L-theanine and ashwagandha blend for sleep quality.',
    safeWording: 'Selected to support your sleep and recovery goals. Commonly used by high-frequency athletes as part of a nightly routine.',
    goalTags: ['recovery', 'health'],
    stimulant: false,
    vegan: true,
    beginner: true,
    stackPriority: 4,
    stackLevels: ['complete'],
    shopifyVariantId: 'mock-014',
    accentColor: '#818cf8',
  },
]
