import type { StackBlueprint } from './types'

export const MOCK_BLUEPRINT: StackBlueprint = {
  id: 'mock-blueprint-001',
  stackName: 'Muscle Building Stack',
  summary: 'A targeted stack to support muscle growth, strength and recovery.',
  primaryGoal: 'muscle',
  secondaryGoals: ['performance', 'recovery'],
  userProfileSummary: '25-34, male, strength training, 3-4x/week',
  slots: [
    {
      slotId: 'slot-protein',
      slotType: 'protein',
      title: 'Protein',
      description: 'Builds and repairs muscle tissue',
      recommendedProductId: 'chrgd-whey-protein',
      selectedProductId: 'chrgd-whey-protein',
      selectedVariantId: null,
      required: true,
      canRemove: false,
      canSwap: true,
      swapGroup: 'protein-whey',
      reason: 'Fast-absorbing protein to build and repair muscle after training.',
      confidenceScore: 95,
      displayOrder: 0,
    },
    {
      slotId: 'slot-performance',
      slotType: 'performance',
      title: 'Performance',
      description: 'Increases strength and power output',
      recommendedProductId: 'chrgd-creatine',
      selectedProductId: 'chrgd-creatine',
      selectedVariantId: null,
      required: true,
      canRemove: false,
      canSwap: true,
      swapGroup: 'creatine',
      reason: 'Proven to build strength and power — take it daily to see results.',
      confidenceScore: 90,
      displayOrder: 1,
    },
    {
      slotId: 'slot-energy',
      slotType: 'energy',
      title: 'Energy / Pre-Workout',
      description: 'Boosts energy and focus before training',
      recommendedProductId: 'chrgd-pre-workout',
      selectedProductId: 'chrgd-pre-workout',
      selectedVariantId: null,
      required: false,
      canRemove: true,
      canSwap: true,
      swapGroup: 'pre-workout-stim',
      reason: 'Boosts energy, focus and blood flow before training.',
      confidenceScore: 75,
      displayOrder: 2,
    },
    {
      slotId: 'slot-hydration',
      slotType: 'hydration',
      title: 'Hydration',
      description: 'Maintains fluid and electrolyte balance',
      recommendedProductId: 'chrgd-electrolytes',
      selectedProductId: 'chrgd-electrolytes',
      selectedVariantId: null,
      required: false,
      canRemove: true,
      canSwap: true,
      swapGroup: 'electrolytes',
      reason: 'Keeps you hydrated and prevents cramps — especially useful in long or sweaty sessions.',
      confidenceScore: 65,
      displayOrder: 3,
    },
    {
      slotId: 'slot-health',
      slotType: 'health',
      title: 'Health',
      description: 'Supports general health and wellbeing',
      recommendedProductId: 'chrgd-omega-3',
      selectedProductId: 'chrgd-omega-3',
      selectedVariantId: null,
      required: false,
      canRemove: true,
      canSwap: true,
      swapGroup: 'omega-3',
      reason: 'Supports heart, brain and joint health — one of the most recommended daily supplements.',
      confidenceScore: 60,
      displayOrder: 4,
    },
  ],
  estimatedOneOffPrice: 108.94,
  estimatedSubscriptionPrice: 92.60,
  savingsSummary: 'Save £16.34/month with a subscription',
  createdAt: '2026-06-12T09:00:00.000Z',
}
