/**
 * CHRGD Mock Product Catalogue
 *
 * This file is the source of truth when the resolved data source is 'mock'
 * (see src/lib/data-source.ts) — i.e. local dev / CI, or when DATA_SOURCE=mock.
 * When the data source is 'shopify', this is replaced by live data fetched via
 * mapShopifyToCatalogueProduct() in src/lib/shopify/catalogue.ts.
 *
 * HOW TO CONNECT SHOPIFY DATA:
 * 1. Set NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN and NEXT_PUBLIC_SHOPIFY_STOREFRONT_TOKEN
 * 2. In Shopify admin, set product tags (goal:*, stack:*, vegan, stimulant, beginner)
 *    and product metafields (chrgd.safe_wording, chrgd.accent_color, etc.)
 * 3. /api/catalogue will automatically serve live data instead of this file
 */

import type { CatalogueProduct } from './types'

export const MOCK_CATALOGUE: CatalogueProduct[] = [
  // ─── PROTEIN SLOT ────────────────────────────────────────────────────────────

  {
    id: 'chrgd-whey-protein',
    title: 'CHRGD Whey Protein',
    handle: 'chrgd-whey-protein',
    description: 'Premium whey isolate with 25g protein per serving. Fast-absorbing for post-workout recovery.',
    imageUrl: null, // replace with real URL when available
    category: 'Protein',
    stackSlots: ['protein'],
    goals: ['muscle', 'recovery', 'bulking'],
    dietaryTags: ['gluten-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-whey-choc-1kg', title: 'Chocolate Fudge / 1kg', flavour: 'Chocolate Fudge', size: '1kg', price: 34.99, compareAtPrice: 44.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-whey-vanilla-1kg', title: 'Vanilla Ice Cream / 1kg', flavour: 'Vanilla Ice Cream', size: '1kg', price: 34.99, compareAtPrice: 44.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-whey-straw-1kg', title: 'Strawberry Milkshake / 1kg', flavour: 'Strawberry Milkshake', size: '1kg', price: 34.99, compareAtPrice: 44.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-whey-choc-2kg', title: 'Chocolate Fudge / 2kg', flavour: 'Chocolate Fudge', size: '2kg', price: 59.99, compareAtPrice: 74.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 34.99,
    compareAtPrice: 44.99,
    subscriptionEligible: true,
    swapGroup: 'protein-whey',
    recommendationPriority: 10,
    marginPriority: 8,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Fast-absorbing protein to build and repair muscle after training.',
    warnings: ['Contains milk (dairy). Not suitable for lactose intolerance.'],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-plant-protein',
    title: 'CHRGD Plant Protein',
    handle: 'chrgd-plant-protein',
    description: 'Complete plant-based protein blend with 22g protein per serving. Pea, rice & hemp.',
    imageUrl: null,
    category: 'Protein',
    stackSlots: ['protein', 'vegan-support'],
    goals: ['muscle', 'recovery', 'health'],
    dietaryTags: ['vegan', 'vegetarian', 'dairy-free', 'gluten-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-plant-choc-1kg', title: 'Chocolate Brownie / 1kg', flavour: 'Chocolate Brownie', size: '1kg', price: 36.99, compareAtPrice: 46.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-plant-vanilla-1kg', title: 'Vanilla Creme / 1kg', flavour: 'Vanilla Creme', size: '1kg', price: 36.99, compareAtPrice: 46.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-plant-unflavoured-1kg', title: 'Unflavoured / 1kg', flavour: 'Unflavoured', size: '1kg', price: 34.99, compareAtPrice: null, available: true, shopifyVariantId: null },
    ],
    basePrice: 36.99,
    compareAtPrice: 46.99,
    subscriptionEligible: true,
    swapGroup: 'protein-plant',
    recommendationPriority: 10,
    marginPriority: 7,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'A complete plant-based protein that covers all essential amino acids.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-mass-builder',
    title: 'CHRGD Mass Builder',
    handle: 'chrgd-mass-builder',
    description: '600kcal mass gainer with 45g protein and complex carbohydrates for serious bulk phases.',
    imageUrl: null,
    category: 'Protein',
    stackSlots: ['protein'],
    goals: ['bulking', 'muscle'],
    dietaryTags: ['gluten-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-mass-choc-4kg', title: 'Chocolate / 4kg', flavour: 'Chocolate', size: '4kg', price: 42.99, compareAtPrice: 54.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-mass-vanilla-4kg', title: 'Vanilla / 4kg', flavour: 'Vanilla', size: '4kg', price: 42.99, compareAtPrice: 54.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 42.99,
    compareAtPrice: 54.99,
    subscriptionEligible: true,
    swapGroup: 'protein-mass',
    recommendationPriority: 8,
    marginPriority: 8,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'High-calorie shake for people trying to gain size and mass.',
    warnings: ['High in calories — only suitable for a calorie surplus phase.'],
    shopifyProductId: null,
  },

  // ─── PERFORMANCE SLOT ────────────────────────────────────────────────────────

  {
    id: 'chrgd-creatine',
    title: 'CHRGD Creatine Monohydrate',
    handle: 'chrgd-creatine',
    description: 'Micronised creatine monohydrate, 5g per serving. The most researched supplement in sport science.',
    imageUrl: null,
    category: 'Performance',
    stackSlots: ['performance'],
    goals: ['muscle', 'performance', 'bulking'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-creatine-unflavoured-500g', title: 'Unflavoured / 500g', flavour: 'Unflavoured', size: '500g', price: 19.99, compareAtPrice: 24.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-creatine-berry-500g', title: 'Mixed Berry / 500g', flavour: 'Mixed Berry', size: '500g', price: 21.99, compareAtPrice: 26.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 19.99,
    compareAtPrice: 24.99,
    subscriptionEligible: true,
    swapGroup: 'creatine',
    recommendationPriority: 9,
    marginPriority: 9,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Proven to build strength and power — take it daily to see results.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── ENERGY SLOT ─────────────────────────────────────────────────────────────

  {
    id: 'chrgd-pre-workout',
    title: 'CHRGD Pre-Workout',
    handle: 'chrgd-pre-workout',
    description: 'Moderate-stimulant pre-workout with caffeine, beta-alanine and L-citrulline for energy and pump.',
    imageUrl: null,
    category: 'Pre-Workout',
    stackSlots: ['energy'],
    goals: ['energy', 'performance', 'muscle'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-preworkout-blue-raz-300g', title: 'Blue Raspberry / 300g', flavour: 'Blue Raspberry', size: '300g', price: 29.99, compareAtPrice: 39.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-preworkout-watermelon-300g', title: 'Watermelon / 300g', flavour: 'Watermelon', size: '300g', price: 29.99, compareAtPrice: 39.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-preworkout-tropical-300g', title: 'Tropical / 300g', flavour: 'Tropical', size: '300g', price: 29.99, compareAtPrice: 39.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 29.99,
    compareAtPrice: 39.99,
    subscriptionEligible: true,
    swapGroup: 'pre-workout-stim',
    recommendationPriority: 8,
    marginPriority: 8,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: true,
    shortReason: 'Boosts energy, focus and blood flow before training.',
    warnings: ['Contains 200mg caffeine per serving. Not suitable for under 18s or those sensitive to caffeine.', 'Do not exceed one serving in 24 hours.'],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-pre-workout-stim-free',
    title: 'CHRGD Stim-Free Pre-Workout',
    handle: 'chrgd-pre-workout-stim-free',
    description: 'Caffeine-free pump formula with L-citrulline, betaine and nitrates for blood flow without stimulants.',
    imageUrl: null,
    category: 'Pre-Workout',
    stackSlots: ['energy'],
    goals: ['energy', 'performance'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-stimfree-cherry-300g', title: 'Cherry Cola / 300g', flavour: 'Cherry Cola', size: '300g', price: 27.99, compareAtPrice: 34.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-stimfree-lemon-300g', title: 'Lemon Sherbet / 300g', flavour: 'Lemon Sherbet', size: '300g', price: 27.99, compareAtPrice: 34.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 27.99,
    compareAtPrice: 34.99,
    subscriptionEligible: true,
    swapGroup: 'pre-workout-stim-free',
    recommendationPriority: 7,
    marginPriority: 7,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Improves blood flow and pump during training — no caffeine.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── HYDRATION SLOT ──────────────────────────────────────────────────────────

  {
    id: 'chrgd-electrolytes',
    title: 'CHRGD Electrolyte Mix',
    handle: 'chrgd-electrolytes',
    description: 'Sodium, potassium and magnesium blend to maintain hydration and prevent cramps during training.',
    imageUrl: null,
    category: 'Hydration',
    stackSlots: ['hydration'],
    goals: ['hydration', 'performance', 'recovery'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-elec-citrus-300g', title: 'Citrus Burst / 300g', flavour: 'Citrus Burst', size: '300g', price: 17.99, compareAtPrice: 22.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-elec-berry-300g', title: 'Mixed Berry / 300g', flavour: 'Mixed Berry', size: '300g', price: 17.99, compareAtPrice: 22.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-elec-unflavoured-300g', title: 'Unflavoured / 300g', flavour: 'Unflavoured', size: '300g', price: 15.99, compareAtPrice: null, available: true, shopifyVariantId: null },
    ],
    basePrice: 17.99,
    compareAtPrice: 22.99,
    subscriptionEligible: true,
    swapGroup: 'electrolytes',
    recommendationPriority: 7,
    marginPriority: 7,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Keeps you hydrated and prevents cramps — especially useful in long or sweaty sessions.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── RECOVERY SLOT ───────────────────────────────────────────────────────────

  {
    id: 'chrgd-bcaa',
    title: 'CHRGD BCAA + Hydration',
    handle: 'chrgd-bcaa',
    description: '2:1:1 BCAA ratio with added electrolytes. Supports muscle recovery and hydration during training.',
    imageUrl: null,
    category: 'Amino Acids',
    stackSlots: ['recovery', 'hydration'],
    goals: ['recovery', 'hydration', 'performance'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-bcaa-passion-390g', title: 'Passion Fruit / 390g', flavour: 'Passion Fruit', size: '390g', price: 24.99, compareAtPrice: 31.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-bcaa-peach-390g', title: 'Peach Mango / 390g', flavour: 'Peach Mango', size: '390g', price: 24.99, compareAtPrice: 31.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 24.99,
    compareAtPrice: 31.99,
    subscriptionEligible: true,
    swapGroup: 'aminos',
    recommendationPriority: 6,
    marginPriority: 6,
    isCoreEligible: true,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Amino acids that speed up muscle repair and reduce soreness.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-collagen',
    title: 'CHRGD Collagen + Vitamin C',
    handle: 'chrgd-collagen',
    description: 'Type I & III collagen peptides with 200mg Vitamin C for enhanced absorption.',
    imageUrl: null,
    category: 'Recovery',
    stackSlots: ['recovery'],
    goals: ['recovery', 'health', 'performance', 'skin-hair-nails', 'immune'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-collagen-unflavoured-300g', title: 'Unflavoured / 300g', flavour: 'Unflavoured', size: '300g', price: 22.99, compareAtPrice: 29.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-collagen-peach-300g', title: 'Peach / 300g', flavour: 'Peach', size: '300g', price: 22.99, compareAtPrice: 29.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 22.99,
    compareAtPrice: 29.99,
    subscriptionEligible: true,
    swapGroup: 'collagen',
    recommendationPriority: 5,
    marginPriority: 6,
    isCoreEligible: false,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Supports joint, tendon and skin health — especially for high-frequency training.',
    warnings: ['Contains bovine collagen. Not suitable for vegans or vegetarians.'],
    shopifyProductId: null,
  },

  // ─── HEALTH SLOT ─────────────────────────────────────────────────────────────

  {
    id: 'chrgd-omega-3',
    title: 'CHRGD Omega-3',
    handle: 'chrgd-omega-3',
    description: 'High-strength fish oil with 1000mg combined EPA & DHA per serving.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['health'],
    goals: ['health', 'recovery', 'focus'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-omega3-90', title: '90 Softgels', flavour: null, size: '90 softgels', price: 14.99, compareAtPrice: 19.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-omega3-180', title: '180 Softgels', flavour: null, size: '180 softgels', price: 26.99, compareAtPrice: 34.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 14.99,
    compareAtPrice: 19.99,
    subscriptionEligible: true,
    swapGroup: 'omega-3',
    recommendationPriority: 6,
    marginPriority: 6,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Supports heart, brain and joint health — one of the most recommended daily supplements.',
    warnings: ['Contains fish. Not suitable for vegans, vegetarians or those with fish allergies.'],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-vitamin-d3-k2',
    title: 'CHRGD Vitamin D3 + K2',
    handle: 'chrgd-vitamin-d3-k2',
    description: 'Vitamin D3 3000IU paired with K2 MK-7 for optimal calcium absorption and bone support.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['health'],
    goals: ['health', 'immune'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-vitd3k2-60', title: '60 Capsules', flavour: null, size: '60 caps', price: 12.99, compareAtPrice: 17.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-vitd3k2-120', title: '120 Capsules', flavour: null, size: '120 caps', price: 22.99, compareAtPrice: 29.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 12.99,
    compareAtPrice: 17.99,
    subscriptionEligible: true,
    swapGroup: 'vitamin-d',
    recommendationPriority: 5,
    marginPriority: 6,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Supports immunity, bone health and energy — especially important for people who train indoors.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-multivitamin',
    title: 'CHRGD Sport Multivitamin',
    handle: 'chrgd-multivitamin',
    description: 'Comprehensive daily multivitamin formulated for people with active lifestyles.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['health'],
    goals: ['health', 'energy', 'performance', 'immune', 'focus'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-multi-60', title: '60 Capsules (1 month)', flavour: null, size: '60 caps', price: 16.99, compareAtPrice: 22.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 16.99,
    compareAtPrice: 22.99,
    subscriptionEligible: true,
    swapGroup: 'multivitamin',
    recommendationPriority: 5,
    marginPriority: 5,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Covers everyday vitamin and mineral gaps to keep you performing at your best.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── SLEEP SLOT ──────────────────────────────────────────────────────────────

  {
    id: 'chrgd-magnesium',
    title: 'CHRGD Magnesium Glycinate',
    handle: 'chrgd-magnesium',
    description: 'Highly bioavailable magnesium glycinate at 400mg per serving. Supports sleep, recovery and nerve function.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['sleep', 'recovery'],
    goals: ['recovery', 'health', 'sleep-better', 'less-stress'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-mag-90', title: '90 Capsules', flavour: null, size: '90 caps', price: 14.99, compareAtPrice: 19.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 14.99,
    compareAtPrice: 19.99,
    subscriptionEligible: true,
    swapGroup: 'magnesium',
    recommendationPriority: 5,
    marginPriority: 6,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Helps you wind down, sleep deeper and recover faster. Take before bed.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-sleep-support',
    title: 'CHRGD Sleep & Recovery',
    handle: 'chrgd-sleep-support',
    description: 'Magnesium, L-theanine and ashwagandha blend formulated to improve sleep quality and overnight recovery.',
    imageUrl: null,
    category: 'Recovery',
    stackSlots: ['sleep', 'recovery'],
    goals: ['recovery', 'health', 'sleep-better', 'less-stress'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-sleep-60', title: '60 Capsules', flavour: null, size: '60 caps', price: 19.99, compareAtPrice: 26.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 19.99,
    compareAtPrice: 26.99,
    subscriptionEligible: true,
    swapGroup: 'sleep-support',
    recommendationPriority: 4,
    marginPriority: 6,
    isCoreEligible: false,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Promotes deep sleep and overnight muscle recovery — take 30 mins before bed.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-ashwagandha',
    title: 'CHRGD Ashwagandha KSM-66',
    handle: 'chrgd-ashwagandha',
    description: 'Clinically-dosed KSM-66 ashwagandha at 600mg to support a calm, balanced response to stress.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['sleep', 'recovery'],
    goals: ['less-stress', 'health', 'menopause'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-ashwa-60', title: '60 Capsules', flavour: null, size: '60 caps', price: 18.99, compareAtPrice: 24.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 18.99,
    compareAtPrice: 24.99,
    subscriptionEligible: true,
    swapGroup: 'adaptogen',
    recommendationPriority: 5,
    marginPriority: 6,
    isCoreEligible: false,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'An adaptogen that helps your body handle stress and wind down in the evening.',
    warnings: ['Not suitable during pregnancy or breastfeeding.'],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-vitamin-c-zinc',
    title: 'CHRGD Vitamin C + Zinc',
    handle: 'chrgd-vitamin-c-zinc',
    description: '1000mg Vitamin C with 15mg Zinc to support everyday immune defence.',
    imageUrl: null,
    category: 'Health',
    stackSlots: ['health'],
    goals: ['immune', 'health'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-vitc-zinc-90', title: '90 Tablets', flavour: null, size: '90 tabs', price: 11.99, compareAtPrice: 15.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 11.99,
    compareAtPrice: 15.99,
    subscriptionEligible: true,
    swapGroup: 'vitamin-c',
    recommendationPriority: 4,
    marginPriority: 5,
    isCoreEligible: true,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'A daily immune top-up — Vitamin C and Zinc both support normal immune function.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── GUT HEALTH SLOT ─────────────────────────────────────────────────────────

  {
    id: 'chrgd-daily-probiotic',
    title: 'CHRGD Daily Probiotic',
    handle: 'chrgd-daily-probiotic',
    description: '10 billion CFU multi-strain probiotic with prebiotic fibre to support a healthy gut microbiome.',
    imageUrl: null,
    category: 'Gut Health',
    stackSlots: ['gut', 'health'],
    goals: ['gut-health', 'health', 'immune'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-probiotic-30', title: '30 Capsules (1 month)', flavour: null, size: '30 caps', price: 21.99, compareAtPrice: 28.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-probiotic-60', title: '60 Capsules (2 months)', flavour: null, size: '60 caps', price: 38.99, compareAtPrice: 49.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 21.99,
    compareAtPrice: 28.99,
    subscriptionEligible: true,
    swapGroup: 'probiotic',
    recommendationPriority: 6,
    marginPriority: 7,
    isCoreEligible: true,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Multi-strain live cultures to support digestion, gut balance and immunity.',
    warnings: [],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-super-greens',
    title: 'CHRGD Super Greens',
    handle: 'chrgd-super-greens',
    description: 'A daily greens blend with 25+ fruits, vegetables, fibre and digestive enzymes.',
    imageUrl: null,
    category: 'Gut Health',
    stackSlots: ['gut', 'health'],
    goals: ['gut-health', 'health', 'immune', 'energy'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['powder'],
    variants: [
      { id: 'chrgd-greens-300g', title: 'Apple & Mint / 300g', flavour: 'Apple & Mint', size: '300g', price: 27.99, compareAtPrice: 34.99, available: true, shopifyVariantId: null },
      { id: 'chrgd-greens-berry-300g', title: 'Mixed Berry / 300g', flavour: 'Mixed Berry', size: '300g', price: 27.99, compareAtPrice: 34.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 27.99,
    compareAtPrice: 34.99,
    subscriptionEligible: true,
    swapGroup: 'greens',
    recommendationPriority: 5,
    marginPriority: 6,
    isCoreEligible: false,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Fibre, greens and digestive enzymes to fill nutritional gaps and support gut health.',
    warnings: [],
    shopifyProductId: null,
  },

  // ─── MENOPAUSE SUPPORT SLOT ──────────────────────────────────────────────────

  {
    id: 'chrgd-menopause-complete',
    title: 'CHRGD Menopause Complete',
    handle: 'chrgd-menopause-complete',
    description: 'Sage, red clover, vitamin B6 and magnesium formulated to support women through perimenopause and menopause.',
    imageUrl: null,
    category: 'Menopause Support',
    stackSlots: ['menopause', 'health'],
    goals: ['menopause', 'health'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-meno-60', title: '60 Capsules (1 month)', flavour: null, size: '60 caps', price: 24.99, compareAtPrice: 32.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 24.99,
    compareAtPrice: 32.99,
    subscriptionEligible: true,
    swapGroup: 'menopause',
    recommendationPriority: 6,
    marginPriority: 7,
    isCoreEligible: true,
    isBoosterEligible: false,
    hasStimulants: false,
    shortReason: 'Botanicals and key nutrients to help with hormonal balance, hot flushes and energy through menopause.',
    warnings: ['Consult your GP before use if you are on hormone-related medication.'],
    shopifyProductId: null,
  },

  {
    id: 'chrgd-meno-bone-support',
    title: 'CHRGD Bone & Joint Support',
    handle: 'chrgd-meno-bone-support',
    description: 'Calcium, vitamin D3, vitamin K2 and magnesium to support bone density — key during and after menopause.',
    imageUrl: null,
    category: 'Menopause Support',
    stackSlots: ['menopause', 'health'],
    goals: ['menopause', 'health'],
    dietaryTags: ['vegan', 'vegetarian', 'gluten-free', 'dairy-free'],
    formats: ['capsules'],
    variants: [
      { id: 'chrgd-meno-bone-90', title: '90 Tablets', flavour: null, size: '90 tabs', price: 17.99, compareAtPrice: 23.99, available: true, shopifyVariantId: null },
    ],
    basePrice: 17.99,
    compareAtPrice: 23.99,
    subscriptionEligible: true,
    swapGroup: 'vitamin-d',
    recommendationPriority: 4,
    marginPriority: 6,
    isCoreEligible: false,
    isBoosterEligible: true,
    hasStimulants: false,
    shortReason: 'Bone-supporting nutrients that become especially important as oestrogen declines.',
    warnings: [],
    shopifyProductId: null,
  },
]
