/**
 * The Pinpoint library, v1 (plan v5 §9). Working content, for pharmacist
 * sign-off before launch.
 *
 * Rules for everything in here:
 *   - Patterns describe habits and situations, never conditions. No pattern is
 *     named after a deficiency or an illness.
 *   - Nothing says what a product does. Product wording comes only from the
 *     claims register, at the results end.
 *   - v1 asks about lifestyle only: sleep timing, caffeine, food habits,
 *     training, daylight and stiffness. Nothing about stress, mood, digestion
 *     or medicines.
 *   - Scenario text stays short enough to fit a phone (about 120 characters).
 */

import { journeyOf } from '../journey'
import { readPlate } from '../plate'
import { caffeineCount, sleepHours } from '../reactions'
import { countsByType, sessionsPerWeek } from '../training'
import type { Food } from '../types'
import { clockWords, dayLine, howOften, quickFire, scenario, thisOrThat } from './define'
import type { Answers, Pattern, PatternId, Probe } from './types'

/* ── Reading the core answers ───────────────────────────────────────────── */

const sessions = (a: Answers) => sessionsPerWeek(a.training)
const by = (a: Answers) => countsByType(a.training)
const drinks = (a: Answers) => caffeineCount(a.caffeine)
const hours = (a: Answers) => (a.sleep ? sleepHours(a.sleep) : null)
const plantBased = (a: Answers) => Boolean(a.plate && readPlate(a.plate).plantBased)
const PROTEIN_FOODS: Food[] = ['oily-fish', 'red-meat', 'poultry', 'eggs', 'dairy', 'beans']
const proteinFoods = (a: Answers) => (a.plate ? a.plate.filter((f) => PROTEIN_FOODS.includes(f)).length : null)
const older = (a: Answers) => a.age === '55-64' || a.age === '65-plus'
const trains = (a: Answers) => sessions(a) >= 1
const endurance = (a: Answers) => by(a).cardio + by(a).sport

/* ── Patterns ───────────────────────────────────────────────────────────── */

export const PATTERNS: Pattern[] = [
  {
    id: 'crash',
    name: 'The 3pm crash',
    line: 'Fine in the morning, flat by mid-afternoon.',
    because: 'For your 3pm crash',
    journeys: ['everyday', 'weight', 'builder', 'ager'],
    prior: -0.9,
    nudges: [
      { when: (a) => a.energy !== null && a.energy <= 4, towards: 'strongly', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
      { when: (a) => a.energy !== null && a.energy >= 5 && a.energy <= 6, towards: 'a little', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
      { when: (a) => a.energy !== null && a.energy >= 8, towards: 'away clearly', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
      { when: (a) => drinks(a) >= 3, towards: 'a little', why: (a) => `${drinks(a)} caffeinated drinks a day` },
      { when: (a) => Boolean(a.changes?.includes('energy')), towards: 'clearly', why: 'Flagging by the afternoon' },
    ],
    effects: [
      { need: 'energy', weight: 4 },
      { need: 'basics', weight: 2 },
    ],
    links: ['energy', 'nutrition'],
  },
  {
    id: 'wired',
    name: 'Wired and tired',
    line: 'Caffeine late in the day, slow to drop off, then a crash.',
    because: 'For being wired and tired',
    journeys: ['everyday', 'builder', 'weight'],
    prior: -1.2,
    nudges: [
      { when: (a) => drinks(a) >= 4, towards: 'strongly', why: (a) => `${drinks(a)} caffeinated drinks a day` },
      { when: (a) => drinks(a) >= 2 && drinks(a) < 4, towards: 'a little', why: (a) => `${drinks(a)} caffeinated drinks a day` },
      { when: (a) => a.caffeine !== null && drinks(a) === 0, towards: 'away strongly', why: 'No caffeine' },
      { when: (a) => a.sleep?.quality === 'broken', towards: 'clearly', why: 'Restless sleep' },
      { when: (a) => a.energy !== null && a.energy <= 4, towards: 'a little', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
    ],
    effects: [
      { need: 'sleep', weight: 4 },
      { need: 'stress', weight: 3 },
    ],
    keepOut: { ingredients: ['caffeine', 'stimulant'], why: 'it’s likely part of what keeps you wired' },
    links: ['sleep', 'energy'],
  },
  {
    id: 'short-sleep',
    name: 'Short on sleep',
    line: 'You drop off fine. There just aren’t enough hours.',
    because: 'For short nights',
    journeys: ['everyday', 'builder', 'weight', 'ager'],
    prior: -1.0,
    nudges: [
      { when: (a) => (hours(a) ?? 8) < 6.5, towards: 'strongly', why: (a) => `About ${hours(a)} hours a night` },
      { when: (a) => (hours(a) ?? 8) >= 6.5 && (hours(a) ?? 8) < 7, towards: 'clearly', why: (a) => `About ${hours(a)} hours a night` },
      { when: (a) => (hours(a) ?? 0) >= 8, towards: 'away strongly', why: (a) => `About ${hours(a)} hours a night` },
      { when: (a) => a.sleep?.quality === 'restful', towards: 'away a little', why: 'Sleeps well' },
    ],
    effects: [
      { need: 'sleep', weight: 4 },
      { need: 'energy', weight: 1 },
    ],
    links: ['sleep', 'energy'],
  },
  {
    id: 'empty',
    name: 'Running on empty',
    line: 'Training or working on not much food.',
    because: 'For running on empty',
    journeys: ['builder', 'everyday'],
    prior: -1.2,
    nudges: [
      { when: (a) => sessions(a) >= 4, towards: 'clearly', why: (a) => `Trains ${sessions(a)} times a week` },
      { when: (a) => a.energy !== null && a.energy <= 4, towards: 'a little', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
      { when: (a) => a.plate !== null && a.plate.length < 4, towards: 'clearly', why: 'A narrow plate most weeks' },
    ],
    effects: [
      { need: 'protein', weight: 3 },
      { need: 'basics', weight: 3 },
      { need: 'energy', weight: 2 },
    ],
    links: ['nutrition', 'training'],
  },
  {
    id: 'protein-gap',
    name: 'Protein gap',
    line: 'Protein at one meal, not three.',
    because: 'For your protein gap',
    journeys: ['builder', 'weight', 'ager'],
    prior: -1.0,
    nudges: [
      { when: (a) => a.aim === 'muscle', towards: 'clearly', why: 'Training to build muscle' },
      { when: plantBased, towards: 'clearly', why: 'A plant-based plate' },
      { when: (a) => (proteinFoods(a) ?? 3) < 2, towards: 'clearly', why: 'Few protein foods most weeks' },
      { when: (a) => (proteinFoods(a) ?? 0) >= 4, towards: 'away a little', why: 'Plenty of protein foods' },
      { when: (a) => Boolean(a.changes?.includes('strength')), towards: 'a little', why: 'Keeping strong is harder' },
    ],
    effects: [{ need: 'protein', weight: 5 }],
    links: ['nutrition', 'training'],
  },
  {
    id: 'not-recovering',
    name: 'Not recovering',
    line: 'Sore for days, and sessions feel heavier than they should.',
    because: 'For recovering between sessions',
    journeys: ['builder'],
    eligible: (a) => sessions(a) >= 2,
    prior: -1.1,
    nudges: [
      { when: (a) => sessions(a) >= 5, towards: 'clearly', why: (a) => `Trains ${sessions(a)} times a week` },
      { when: (a) => a.intensity === 'hard', towards: 'clearly', why: 'Most sessions flat out' },
      { when: (a) => (hours(a) ?? 8) < 7, towards: 'a little', why: (a) => `About ${hours(a)} hours a night` },
      { when: (a) => (a.body?.length ?? 0) > 0, towards: 'a little', why: 'Sore spots' },
    ],
    effects: [
      { need: 'recovery', weight: 4 },
      { need: 'sleep', weight: 2 },
      { need: 'protein', weight: 2 },
    ],
    links: ['recovery', 'training'],
  },
  {
    id: 'caffeine-train',
    name: 'Caffeine to train',
    line: 'A pre-workout on top of your coffee, and sleep pays for it.',
    because: 'For training on caffeine',
    journeys: ['builder'],
    eligible: (a) => sessions(a) >= 2,
    prior: -1.4,
    nudges: [
      { when: (a) => Boolean(a.shelf?.includes('pre-workout')), towards: 'strongly', why: 'Already takes a pre-workout' },
      { when: (a) => drinks(a) >= 3, towards: 'a little', why: (a) => `${drinks(a)} caffeinated drinks a day` },
      { when: (a) => a.sleep?.quality === 'broken', towards: 'a little', why: 'Restless sleep' },
    ],
    effects: [{ need: 'sleep', weight: 3 }],
    keepOut: { ingredients: ['stimulant'], why: 'a stimulant pre-workout on top of your coffee is likely costing you sleep' },
    links: ['training', 'sleep'],
  },
  {
    id: 'sweat',
    name: 'Sweat it out',
    line: 'Long or hot sessions, and you lose a lot of salt and water.',
    because: 'For long, sweaty sessions',
    journeys: ['builder'],
    eligible: (a) => endurance(a) >= 1 || a.aim === 'endurance' || a.aim === 'sport',
    prior: -1.2,
    nudges: [
      { when: (a) => a.aim === 'endurance', towards: 'strongly', why: 'Training to go further' },
      { when: (a) => a.aim === 'sport', towards: 'clearly', why: 'Training for your sport' },
      { when: (a) => endurance(a) >= 3, towards: 'clearly', why: (a) => `${endurance(a)} cardio or sport sessions a week` },
    ],
    effects: [{ need: 'hydration', weight: 5 }],
    links: ['training', 'recovery'],
  },
  {
    id: 'plant-gap',
    name: 'Plant-powered gap',
    line: 'Plant-based and active, so protein and B12 run light.',
    because: 'For a plant-based plate',
    journeys: ['builder', 'everyday', 'weight', 'ager'],
    eligible: plantBased,
    prior: -0.2,
    nudges: [
      { when: (a) => sessions(a) >= 3, towards: 'clearly', why: (a) => `Trains ${sessions(a)} times a week` },
      { when: (a) => Boolean(a.shelf?.includes('multivitamin')), towards: 'away a little', why: 'Already takes a multivitamin' },
    ],
    effects: [
      { need: 'protein', weight: 3 },
      { need: 'b12-iron', weight: 4 },
    ],
    links: ['nutrition', 'energy'],
  },
  {
    id: 'indoor',
    name: 'Indoor life',
    line: 'Dark commutes, a desk all day, not much daylight.',
    because: 'For an indoor life',
    journeys: ['everyday', 'builder', 'weight', 'ager'],
    prior: -0.9,
    nudges: [
      { when: (a) => a.daylight === 'hardly', towards: 'strongly', why: 'Rarely outside in daylight' },
      { when: (a) => a.daylight === 'some', towards: 'clearly', why: 'Outside in daylight 1–2 days a week' },
      { when: (a) => a.daylight === 'most', towards: 'away clearly', why: 'Outside most days' },
      { when: (a) => a.daylight === 'daily', towards: 'away strongly', why: 'Outside every day' },
    ],
    effects: [{ need: 'low-sun', weight: 5 }],
    links: ['daylight', 'energy'],
  },
  {
    id: 'weekend-warrior',
    name: 'Weekend warrior',
    line: 'Quiet in the week, then big efforts crammed into the weekend.',
    because: 'For your weekend efforts',
    journeys: ['builder', 'everyday'],
    eligible: trains,
    prior: -1.5,
    nudges: [
      { when: (a) => by(a).sport >= 1, towards: 'clearly', why: 'Plays sport' },
      { when: (a) => sessions(a) <= 3, towards: 'a little', why: (a) => `${sessions(a)} sessions a week` },
      { when: (a) => (a.body?.length ?? 0) > 0, towards: 'a little', why: 'Sore spots' },
    ],
    effects: [
      { need: 'recovery', weight: 3 },
      { need: 'joints', weight: 2 },
    ],
    links: ['training', 'recovery'],
  },
  {
    id: 'stiff-starter',
    name: 'Stiff starter',
    line: 'Stiff first thing, easier once you’re moving.',
    because: 'For stiff starts',
    journeys: ['ager'],
    prior: -0.5,
    nudges: [
      { when: (a) => (a.body?.length ?? 0) > 0, towards: 'clearly', why: 'Joints that need looking after' },
      { when: (a) => Boolean(a.changes?.includes('getting-about')), towards: 'strongly', why: 'Getting about is harder' },
      { when: (a) => a.body !== null && a.body.length === 0, towards: 'away a little', why: 'Nothing sore' },
    ],
    effects: [
      { need: 'joints', weight: 4 },
      { need: 'collagen', weight: 2 },
      { need: 'omega', weight: 2 },
    ],
    links: ['recovery', 'training'],
  },
  {
    id: 'keeping-strong',
    name: 'Keeping strong',
    line: 'Stairs, shopping bags and jars getting harder than they were.',
    because: 'For keeping strong',
    journeys: ['ager'],
    prior: -0.7,
    nudges: [
      { when: (a) => Boolean(a.changes?.includes('strength')), towards: 'strongly', why: 'Keeping strong is harder' },
      { when: (a) => a.training !== null && by(a).gym === 0, towards: 'a little', why: 'No strength sessions' },
      { when: (a) => (proteinFoods(a) ?? 3) < 2, towards: 'clearly', why: 'Few protein foods most weeks' },
    ],
    // Creatine for older adults only after pharmacist sign-off (plan v5 §9).
    effects: [
      { need: 'protein', weight: 4 },
      { need: 'low-sun', weight: 2 },
    ],
    links: ['training', 'nutrition'],
  },
  {
    id: 'staying-sharp',
    name: 'Staying sharp',
    line: 'Names, keys, losing the thread more than you used to.',
    because: 'For staying sharp',
    journeys: ['ager', 'everyday'],
    eligible: (a) => journeyOf(a) === 'ager' || a.goals.includes('focus'),
    prior: -0.8,
    nudges: [
      { when: (a) => Boolean(a.changes?.includes('staying-sharp')), towards: 'strongly', why: 'Staying sharp matters to you' },
      { when: (a) => a.goals.includes('focus'), towards: 'clearly', why: 'Focus is one of your goals' },
      { when: (a) => Boolean(a.plate && readPlate(a.plate).noOilyFish), towards: 'a little', why: 'No oily fish most weeks' },
    ],
    effects: [
      { need: 'omega', weight: 4 },
      { need: 'focus', weight: 2 },
      { need: 'b12-iron', weight: 2 },
    ],
    links: ['energy', 'nutrition'],
  },
  {
    id: 'broken-nights',
    name: 'Broken nights',
    line: 'Awake in the small hours, and slow to get back off.',
    because: 'For broken nights',
    journeys: ['ager', 'everyday'],
    prior: -1.0,
    nudges: [
      { when: (a) => a.sleep?.quality === 'broken', towards: 'strongly', why: 'Restless sleep' },
      { when: (a) => Boolean(a.changes?.includes('sleeping-through')), towards: 'strongly', why: 'Waking in the night' },
      { when: older, towards: 'a little', why: 'Sleep gets lighter with age' },
      { when: (a) => a.sleep?.quality === 'restful', towards: 'away clearly', why: 'Sleeps well' },
    ],
    effects: [{ need: 'sleep', weight: 4 }],
    links: ['sleep', 'recovery'],
  },
  {
    id: 'eating-less',
    name: 'Eating less, running low',
    line: 'Smaller meals than you used to, and you’re flagging.',
    because: 'For eating less',
    journeys: ['weight'],
    prior: -0.6,
    nudges: [
      { when: (a) => a.goals[0] === 'weight', towards: 'clearly', why: 'Weight loss is your top goal' },
      { when: (a) => a.plate !== null && a.plate.length < 4, towards: 'a little', why: 'A narrow plate most weeks' },
      { when: (a) => a.energy !== null && a.energy <= 4, towards: 'a little', why: (a) => `Energy ${a.energy}/10 by the afternoon` },
    ],
    effects: [
      { need: 'protein', weight: 4 },
      { need: 'basics', weight: 3 },
    ],
    links: ['nutrition', 'energy'],
  },
]

/* ── Probes ─────────────────────────────────────────────────────────────── */

const NOT_AGER = (a: Answers) => journeyOf(a) !== 'ager'
const AGER = (a: Answers) => journeyOf(a) === 'ager'

export const PROBES: Probe[] = [
  /* Move: training and energy */
  thisOrThat({
    id: 'pre-session',
    area: 'move',
    askIf: trains,
    question: 'Before a session, you…',
    a: { text: 'Train on empty, or on a coffee.', said: 'Trains on empty', points: { empty: 'strongly', 'caffeine-train': 'a little' } },
    b: { text: 'Eat something proper an hour or two before.', said: 'Eats before training', points: {} },
  }),
  howOften({
    id: 'heavy-legs',
    area: 'move',
    askIf: (a) => sessions(a) >= 2,
    scene: 'Two days after training',
    text: 'Your legs still feel heavy, and sessions feel harder than they should.',
    said: 'Heavy legs for days',
    points: { 'not-recovering': 'strongly', empty: 'a little' },
  }),
  howOften({
    id: 'stairs-sideways',
    area: 'move',
    askIf: (a) => by(a).gym >= 1,
    scene: 'Two days after leg day',
    text: 'You’re still taking the stairs sideways.',
    said: 'Still sore two days later',
    points: { 'not-recovering': 'clearly', 'weekend-warrior': 'a little' },
  }),
  scenario({
    id: 'after-match',
    area: 'move',
    askIf: (a) => endurance(a) >= 1,
    scene: 'The day after a match or a long run',
    text: 'You’re wrecked all day, then fine again by midweek.',
    said: 'Wrecked the day after',
    points: { 'weekend-warrior': 'strongly', 'not-recovering': 'a little' },
  }),
  scenario({
    id: 'quiet-weekdays',
    area: 'move',
    askIf: trains,
    scene: 'Your week',
    text: 'Quiet on weekdays, then you go all out at the weekend.',
    said: 'All out at weekends',
    points: { 'weekend-warrior': 'strongly' },
  }),
  scenario({
    id: 'pre-workout-coffee',
    area: 'move',
    askIf: (a) => sessions(a) >= 2,
    scene: 'Gym days',
    text: 'A pre-workout on top of your usual coffee. Sometimes two.',
    said: 'Pre-workout on top of coffee',
    points: { 'caffeine-train': 'strongly', wired: 'clearly' },
  }),
  dayLine({
    id: 'train-when',
    area: 'move',
    askIf: (a) => sessions(a) >= 2,
    question: 'When do you usually train?',
    hint: 'Drag to a normal training day.',
    line: { from: 6 * 60, to: 23 * 60, step: 30, start: 18 * 60, said: (m) => `Trains around ${clockWords(m)}` },
    buckets: [
      { key: 'early', until: 9 * 60 },
      { key: 'day', until: 17 * 60 },
      { key: 'evening', until: 20 * 60, points: { 'caffeine-train': 'a little' } },
      { key: 'late', until: 23 * 60, points: { 'caffeine-train': 'clearly', 'not-recovering': 'a little', wired: 'a little' } },
    ],
    extras: [{ key: 'varies', label: 'It varies' }],
  }),
  scenario({
    id: 'salt-marks',
    area: 'move',
    askIf: (a) => endurance(a) >= 1 || a.aim === 'endurance' || a.aim === 'sport',
    scene: 'After a long or hot session',
    text: 'White salt marks on your kit, and you’re gasping for a drink.',
    said: 'Salt marks on your kit',
    points: { sweat: 'strongly' },
  }),
  howOften({
    id: 'cramp',
    area: 'move',
    askIf: (a) => endurance(a) >= 1 || a.aim === 'endurance' || a.aim === 'sport',
    scene: 'In long sessions',
    text: 'Your calves cramp, or you feel washed out afterwards.',
    said: 'Cramp or washed out after long sessions',
    points: { sweat: 'clearly', 'not-recovering': 'a little' },
  }),
  quickFire({
    id: 'training-habits',
    area: 'move',
    askIf: (a) => sessions(a) >= 3,
    hint: 'Yes or no. Don’t overthink it.',
    items: [
      { key: 'twice', text: 'Train twice in a day sometimes?', points: { 'not-recovering': 'a little', sweat: 'a little' }, yes: 'Trains twice a day sometimes' },
      { key: 'rest-day', text: 'At least one full rest day a week?', points: { 'not-recovering': 'away clearly' }, no: 'No full rest day' },
      { key: 'lighter', text: 'A lighter week every month or two?', points: { 'not-recovering': 'away a little' }, no: 'No lighter weeks' },
    ],
  }),
  scenario({
    id: 'three-pm',
    area: 'move',
    scene: 'A weekday · 3pm',
    text: 'You’ve read the same email three times, and you’re eyeing the biscuits.',
    said: 'Flat by 3pm',
    points: { crash: 'strongly', empty: 'a little', wired: 'a little' },
    askIf: NOT_AGER,
  }),
  scenario({
    id: 'three-pm-ager',
    area: 'move',
    askIf: AGER,
    scene: 'Mid-afternoon',
    text: 'After lunch you need a sit-down, and your eyes start to close.',
    said: 'Flagging after lunch',
    points: { crash: 'strongly', 'broken-nights': 'a little' },
  }),
  dayLine({
    id: 'slump-when',
    area: 'move',
    question: 'When does your energy dip?',
    hint: 'Drag to when it usually hits.',
    line: { from: 7 * 60, to: 22 * 60, step: 30, start: 15 * 60, said: (m) => `Energy dips around ${clockWords(m)}` },
    buckets: [
      { key: 'morning', until: 11 * 60, points: { 'short-sleep': 'clearly', wired: 'a little' } },
      { key: 'lunch', until: 14 * 60, points: { crash: 'clearly' } },
      { key: 'afternoon', until: 17 * 60 + 30, points: { crash: 'strongly' } },
      { key: 'evening', until: 22 * 60 },
    ],
    extras: [{ key: 'never', label: 'It doesn’t really', points: { crash: 'away strongly', 'short-sleep': 'away a little' } }],
  }),
  thisOrThat({
    id: 'mornings-or-afternoons',
    area: 'move',
    a: { text: 'Slow to get going. Better by lunch.', said: 'Slow to get going', points: { 'short-sleep': 'clearly', wired: 'a little' } },
    b: { text: 'Fine in the morning. Flat by mid-afternoon.', said: 'Flat by mid-afternoon', points: { crash: 'strongly' } },
  }),
  scenario({
    id: 'crash-some-days',
    area: 'move',
    askIf: (a) => a.energy !== null && a.energy >= 7,
    scene: 'Just checking',
    text: (a) => `You said your energy’s about ${a.energy}/10. But some afternoons still hit you like a wall.`,
    said: 'Some afternoons hit like a wall',
    points: { crash: 'clearly' },
  }),
  scenario({
    id: 'running-on-fumes',
    area: 'move',
    askIf: (a) => a.goals.includes('weight'),
    scene: 'Since eating less',
    text: 'By mid-afternoon you’re running on fumes.',
    said: 'Running on fumes by mid-afternoon',
    points: { 'eating-less': 'strongly', crash: 'a little' },
  }),

  /* Rest: sleep and daylight */
  thisOrThat({
    id: 'eleven-pm',
    area: 'rest',
    a: { text: '11pm. Lights off, mind racing. Still awake at midnight.', said: 'Mind racing at 11pm', points: { wired: 'strongly' } },
    b: { text: '11pm. Still up. Head hits the pillow, gone in minutes.', said: 'Out like a light, just late', points: { 'short-sleep': 'strongly' } },
    askIf: NOT_AGER,
  }),
  howOften({
    id: 'snooze',
    area: 'rest',
    scene: 'Mornings',
    text: 'You hit snooze more than once.',
    said: 'Snoozes',
    points: { 'short-sleep': 'strongly', wired: 'a little' },
    askIf: NOT_AGER,
  }),
  scenario({
    id: 'weekend-lie-in',
    area: 'rest',
    scene: 'Weekends',
    text: 'Given the chance, you sleep two hours longer at weekends.',
    said: 'Sleeps in at weekends',
    points: { 'short-sleep': 'strongly' },
    askIf: NOT_AGER,
  }),
  howOften({
    id: 'awake-3am',
    area: 'rest',
    scene: '3am',
    text: 'You wake in the night and lie there for a while.',
    said: 'Awake in the night',
    points: { 'broken-nights': 'strongly', wired: 'a little' },
  }),
  scenario({
    id: 'back-off',
    area: 'rest',
    askIf: (a) => a.sleep?.quality !== 'restful',
    scene: 'In the night',
    text: 'Once you’re awake, it’s an hour before you drop off again.',
    said: 'Slow to get back off',
    points: { 'broken-nights': 'strongly', wired: 'a little' },
  }),
  thisOrThat({
    id: 'early-waking',
    area: 'rest',
    askIf: (a) => a.sleep?.quality !== 'restful',
    a: { text: 'Wake at 4 or 5 and can’t get back off.', said: 'Wakes too early', points: { 'broken-nights': 'strongly' } },
    b: { text: 'Wake a few times, but drop straight back off.', said: 'Wakes, then back off', points: { 'broken-nights': 'a little' } },
  }),
  scenario({
    id: 'phone-in-bed',
    area: 'rest',
    scene: 'Evenings',
    text: 'Phone in bed, still scrolling after midnight.',
    said: 'Scrolling after midnight',
    points: { 'short-sleep': 'clearly', wired: 'a little' },
    askIf: NOT_AGER,
  }),
  scenario({
    id: 'tired-then-awake',
    area: 'rest',
    scene: 'Bedtime',
    text: 'Exhausted all day, then wide awake the moment you get into bed.',
    said: 'Wide awake at bedtime',
    points: { wired: 'strongly' },
  }),
  quickFire({
    id: 'sleep-habits',
    area: 'rest',
    askIf: NOT_AGER,
    hint: 'Yes or no. Don’t overthink it.',
    items: [
      { key: 'early-alarm', text: 'Alarm before 6:30am on workdays?', points: { 'short-sleep': 'clearly' }, yes: 'Early alarm' },
      { key: 'screens', text: 'Screens in bed most nights?', points: { 'short-sleep': 'a little', wired: 'a little' }, yes: 'Screens in bed' },
      { key: 'nap', text: 'Nod off in the afternoon?', points: { 'short-sleep': 'clearly', crash: 'a little' }, yes: 'Nods off in the afternoon' },
    ],
  }),
  scenario({
    id: 'workday-daylight',
    area: 'rest',
    askIf: NOT_AGER,
    scene: 'A workday',
    text: 'You don’t see daylight until you leave work.',
    said: 'No daylight till after work',
    points: { indoor: 'strongly' },
  }),
  scenario({
    id: 'clocks-back',
    area: 'rest',
    scene: 'Winter',
    text: 'Your energy drops when the clocks go back.',
    said: 'Worse in winter',
    points: { indoor: 'clearly', crash: 'a little' },
  }),
  thisOrThat({
    id: 'lunchtime',
    area: 'rest',
    askIf: NOT_AGER,
    question: 'A normal weekday lunchtime?',
    a: { text: 'At my desk, or indoors somewhere.', said: 'Lunch indoors', points: { indoor: 'clearly' } },
    b: { text: 'Outside for a bit, even a short walk.', said: 'Outside at lunch', points: {} },
  }),
  scenario({
    id: 'dark-commute',
    area: 'rest',
    askIf: NOT_AGER,
    scene: 'Winter commute',
    text: 'Dark when you leave, dark when you get home.',
    said: 'Commutes in the dark',
    points: { indoor: 'strongly' },
  }),
  scenario({
    id: 'mostly-in',
    area: 'rest',
    askIf: AGER,
    scene: 'A normal day',
    text: 'Most days you’re indoors, apart from a quick trip out.',
    said: 'Mostly indoors',
    points: { indoor: 'strongly' },
  }),

  /* Fuel: caffeine and food */
  dayLine({
    id: 'last-caffeine',
    area: 'fuel',
    askIf: (a) => drinks(a) >= 1,
    question: 'When’s your last caffeine?',
    hint: 'Drag the cup to a normal weekday.',
    line: { from: 6 * 60, to: 24 * 60, step: 30, start: 13 * 60, said: (m) => `Last caffeine about ${clockWords(m)}` },
    buckets: [
      { key: 'morning', until: 12 * 60, points: { wired: 'away clearly' } },
      { key: 'early-afternoon', until: 15 * 60, points: { wired: 'a little' } },
      { key: 'late-afternoon', until: 18 * 60, points: { wired: 'strongly', crash: 'a little' } },
      { key: 'evening', until: 24 * 60, points: { wired: 'strongly' } },
    ],
    extras: [{ key: 'varies', label: 'It varies' }],
  }),
  scenario({
    id: 'breakfast-coffee',
    area: 'fuel',
    scene: 'Mornings',
    text: 'Breakfast is a coffee. Or nothing.',
    said: 'Breakfast is a coffee',
    points: { empty: 'strongly', crash: 'clearly' },
    askIf: NOT_AGER,
  }),
  quickFire({
    id: 'protein-meals',
    area: 'fuel',
    question: 'Protein at…',
    hint: 'Meat, fish, eggs, dairy, tofu or beans. About a palm-sized portion.',
    items: [
      { key: 'breakfast', text: 'Breakfast?', points: { 'protein-gap': 'away clearly' }, no: 'No protein at breakfast' },
      { key: 'lunch', text: 'Lunch?', points: { 'protein-gap': 'away clearly', empty: 'away a little' }, no: 'No protein at lunch' },
      { key: 'dinner', text: 'Dinner?', points: { 'protein-gap': 'away a little' }, no: 'No protein at dinner' },
    ],
  }),
  scenario({
    id: 'one-protein-meal',
    area: 'fuel',
    scene: 'Food',
    text: 'Protein at every meal? Honestly, one meal at most.',
    said: 'Protein at one meal',
    points: { 'protein-gap': 'strongly', 'plant-gap': 'clearly', empty: 'a little' },
  }),
  scenario({
    id: 'fortified',
    area: 'fuel',
    askIf: plantBased,
    scene: 'Food',
    text: 'You don’t really use fortified foods, like plant milks or cereals with B12.',
    said: 'Few fortified foods',
    points: { 'plant-gap': 'strongly' },
  }),
  thisOrThat({
    id: 'plant-protein',
    area: 'fuel',
    askIf: plantBased,
    question: 'Your protein mostly comes from…',
    a: { text: 'Tofu, tempeh, lentils or a plant shake most days.', said: 'Plant protein most days', points: { 'plant-gap': 'away clearly' } },
    b: { text: 'Bread, pasta and whatever’s around.', said: 'Not much plant protein', points: { 'plant-gap': 'strongly' } },
  }),
  scenario({
    id: 'sweet-fix',
    area: 'fuel',
    scene: 'Mid-afternoon',
    text: 'You reach for something sweet, or another coffee, to keep going.',
    said: 'Reaches for sugar or coffee',
    points: { crash: 'clearly', wired: 'a little' },
  }),
  howOften({
    id: 'skip-lunch',
    area: 'fuel',
    askIf: NOT_AGER,
    scene: 'Busy days',
    text: 'You skip lunch, or eat it at your desk in five minutes.',
    said: 'Skips lunch',
    points: { empty: 'clearly', crash: 'clearly' },
  }),
  scenario({
    id: 'smaller-meals',
    area: 'fuel',
    askIf: (a) => a.goals.includes('weight'),
    scene: 'Lately',
    text: 'Your meals are a lot smaller than they used to be.',
    said: 'Much smaller meals',
    points: { 'eating-less': 'strongly', 'protein-gap': 'a little' },
  }),
  thisOrThat({
    id: 'lunch-now',
    area: 'fuel',
    askIf: (a) => a.goals.includes('weight'),
    question: 'A normal lunch now looks like…',
    a: { text: 'A proper meal, just smaller.', said: 'Smaller proper meals', points: { 'eating-less': 'a little' } },
    b: { text: 'A snack, or I forget.', said: 'Lunch is a snack, or nothing', points: { 'eating-less': 'strongly', 'protein-gap': 'clearly' } },
  }),
  scenario({
    id: 'first-coffee',
    area: 'fuel',
    askIf: (a) => drinks(a) >= 3,
    scene: 'Before 10am',
    text: 'Without your coffee you’d barely function.',
    said: 'Needs coffee to function',
    points: { wired: 'clearly', 'short-sleep': 'a little' },
  }),

  /* Body: joints, strength, staying sharp */
  thisOrThat({
    id: 'stiff-when',
    area: 'body',
    askIf: (a) => AGER(a) || (a.body?.length ?? 0) > 0,
    a: { text: 'Stiff first thing, easier once I’m moving.', said: 'Stiff first thing', points: { 'stiff-starter': 'strongly' } },
    b: { text: 'Fine in the morning, stiff after sitting a while.', said: 'Stiff after sitting', points: { 'stiff-starter': 'a little' } },
  }),
  howOften({
    id: 'low-chair',
    area: 'body',
    askIf: AGER,
    scene: 'Around the house',
    text: 'Getting up from a low chair takes a push on the arms.',
    said: 'A low chair takes a push',
    points: { 'keeping-strong': 'strongly' },
  }),
  scenario({
    id: 'shopping-bags',
    area: 'body',
    askIf: AGER,
    scene: 'Coming home',
    text: 'Carrying the shopping in from the car feels harder than it did.',
    said: 'Shopping bags feel heavier',
    points: { 'keeping-strong': 'clearly' },
  }),
  scenario({
    id: 'stairs-effort',
    area: 'body',
    askIf: AGER,
    scene: 'Stairs',
    text: 'The stairs take a bit more effort than they did a year ago.',
    said: 'Stairs take more effort',
    points: { 'keeping-strong': 'clearly', 'stiff-starter': 'a little' },
  }),
  thisOrThat({
    id: 'names-keys',
    area: 'body',
    question: 'When a name or your keys go missing…',
    a: { text: 'It’s when I’m tired. Otherwise I’m sharp.', said: 'Foggy when tired', points: { 'staying-sharp': 'a little', 'short-sleep': 'a little' } },
    b: { text: 'It happens most days now.', said: 'Forgetful most days', points: { 'staying-sharp': 'strongly' } },
  }),
  howOften({
    id: 'lose-thread',
    area: 'body',
    scene: 'Talking to someone',
    text: 'You lose your thread halfway through a sentence.',
    said: 'Loses the thread',
    points: { 'staying-sharp': 'clearly', 'short-sleep': 'a little' },
  }),
  scenario({
    id: 'focus-after-lunch',
    area: 'body',
    askIf: (a) => a.goals.includes('focus'),
    scene: 'After lunch',
    text: 'Your focus goes, however hard you try.',
    said: 'Focus goes after lunch',
    points: { crash: 'clearly', 'staying-sharp': 'a little' },
  }),
  scenario({
    id: 'ache-after-more',
    area: 'body',
    askIf: (a) => (a.body?.length ?? 0) > 0,
    scene: 'The day after',
    text: 'Your joints ache the day after you’ve done more than usual.',
    said: 'Aches after doing more',
    points: { 'weekend-warrior': 'clearly', 'stiff-starter': 'clearly' },
  }),
  scenario({
    id: 'sitting-day',
    area: 'body',
    scene: 'A normal day',
    text: 'Most of it is sitting: desk, car, sofa.',
    said: 'Sits most of the day',
    points: { 'stiff-starter': 'a little', indoor: 'a little' },
  }),

  /* Telling overlapping patterns apart */
  thisOrThat({
    id: 'after-lunch',
    area: 'fuel',
    question: 'After a proper lunch, you…',
    a: { text: 'Perk up. It was food I needed.', said: 'Perks up after food', points: { empty: 'strongly' } },
    b: { text: 'Still flag, food or no food.', said: 'Flags whatever you eat', points: { crash: 'clearly' } },
  }),
  thisOrThat({
    id: 'which-nights',
    area: 'rest',
    question: 'Your nights are more…',
    a: { text: 'Hard to get to sleep in the first place.', said: 'Hard to get to sleep', points: { wired: 'strongly' } },
    b: { text: 'Asleep fine, but awake in the small hours.', said: 'Awake in the small hours', points: { 'broken-nights': 'strongly' } },
  }),
  thisOrThat({
    id: 'meal-size',
    area: 'fuel',
    question: 'Your meals are…',
    a: { text: 'Big enough, just light on meat, fish, eggs or beans.', said: 'Light on protein', points: { 'protein-gap': 'strongly' } },
    b: { text: 'Small, or skipped when I’m busy.', said: 'Small or skipped meals', points: { empty: 'strongly' } },
  }),

  /* More ways in, for the patterns with few */
  howOften({
    id: 'whole-days-in',
    area: 'rest',
    scene: 'Winter',
    text: 'A whole day goes by without you stepping outside.',
    said: 'Whole days indoors',
    points: { indoor: 'strongly' },
  }),
  quickFire({
    id: 'outdoors',
    area: 'rest',
    hint: 'Yes or no. A normal week.',
    items: [
      { key: 'walk', text: 'A walk outside most days?', points: { indoor: 'away clearly' }, no: 'Rarely walks outside' },
      { key: 'green', text: 'Time in a garden or park most weeks?', points: { indoor: 'away a little' }, no: 'Little time outdoors' },
      { key: 'car', text: 'Car door to door, most journeys?', points: { indoor: 'a little' }, yes: 'Car door to door' },
    ],
  }),
  scenario({
    id: 'late-and-early',
    area: 'rest',
    askIf: AGER,
    scene: 'Evenings',
    text: 'Up late with the TV, then awake early anyway.',
    said: 'Up late, awake early',
    points: { 'short-sleep': 'strongly', 'broken-nights': 'a little' },
  }),
  scenario({
    id: 'tip-of-tongue',
    area: 'body',
    scene: 'Mid-conversation',
    text: 'The word you want is on the tip of your tongue, more often than it was.',
    said: 'Words on the tip of the tongue',
    points: { 'staying-sharp': 'strongly' },
  }),
  thisOrThat({
    id: 'lists',
    area: 'body',
    question: 'To remember things, you…',
    a: { text: 'Keep it all in my head, no problem.', said: 'Remembers without lists', points: { 'staying-sharp': 'away clearly' } },
    b: { text: 'Need lists and reminders more than I used to.', said: 'Needs more reminders', points: { 'staying-sharp': 'clearly' } },
  }),
  scenario({
    id: 'shattered-awake',
    area: 'move',
    askIf: (a) => sessions(a) >= 2,
    scene: 'After a hard session',
    text: 'You sleep badly, even though you’re shattered.',
    said: 'Sleeps badly after hard sessions',
    points: { 'not-recovering': 'clearly', wired: 'a little' },
  }),
  scenario({
    id: 'stalled',
    area: 'move',
    askIf: (a) => by(a).gym >= 1,
    scene: 'Lately',
    text: 'Your lifts have stalled, or gone backwards, for weeks.',
    said: 'Lifts stalled for weeks',
    points: { 'not-recovering': 'strongly' },
  }),
  thisOrThat({
    id: 'gym-nights',
    area: 'move',
    askIf: (a) => sessions(a) >= 2,
    question: 'On nights after you train, you…',
    a: { text: 'Lie awake buzzing for hours.', said: 'Buzzing after training', points: { 'caffeine-train': 'strongly', wired: 'a little' } },
    b: { text: 'Sleep better than usual.', said: 'Sleeps better after training', points: { 'caffeine-train': 'away a little' } },
  }),
  howOften({
    id: 'monday-sore',
    area: 'move',
    askIf: trains,
    scene: 'Monday mornings',
    text: 'You’re stiffer and sorer than on any other day of the week.',
    said: 'Sore on Mondays',
    points: { 'weekend-warrior': 'strongly' },
  }),
  quickFire({
    id: 'plant-staples',
    area: 'fuel',
    askIf: plantBased,
    hint: 'Yes or no. A normal week.',
    items: [
      { key: 'milk', text: 'Fortified plant milk most days?', points: { 'plant-gap': 'away clearly' }, no: 'No fortified plant milk' },
      { key: 'tofu', text: 'Tofu, tempeh or lentils most days?', points: { 'plant-gap': 'away clearly' }, no: 'Little plant protein' },
      { key: 'b12', text: 'Already take anything with B12?', points: { 'plant-gap': 'away strongly' }, no: 'No B12 yet' },
    ],
  }),
]

export const PATTERN_BY_ID = Object.fromEntries(PATTERNS.map((p) => [p.id, p])) as Record<PatternId, Pattern>
export const PROBE_BY_ID: Record<string, Probe> = Object.fromEntries(PROBES.map((p) => [p.id, p]))
