/**
 * The film grain tile, inlined.
 *
 * `--grain-opacity` is not decoration in this design: large soft gradients band
 * visibly on an 8-bit display, and the card is a 1080px frame carrying three of
 * them. Grain is what breaks the bands up and gives the black something to be
 * made of.
 *
 * On screen the app tiles a PNG. Satori resolves no external URLs and runs no
 * SVG filters, so the tile arrives as a data URI: 64x64, 8-bit greyscale,
 * gaussian around mid-grey, laid over the ground at `--grain-opacity`. Noise
 * does not compress, so ~4KB is close to the floor for a tile large enough not
 * to show its own repeat.
 *
 * Generated by the snippet in `docs/SHARE_CARD_BLUEPRINT.md` (deterministic —
 * the same seed and parameters reproduce these bytes exactly).
 */
export const GRAIN_TILE_PX = 64

export const GRAIN_DATA_URI =
  'data:image/png;base64,' +
  'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAAAAACPAi4CAAAPoUlEQVR42gXBB1SbB2IA4D9J28tLbyRNes+99DKceIDx' +
  'iCc2w9iA2UIgQCChgfbee/zaC+29BVpICIkpwEzb4D3wiOMMu+ckvkt7adO73jXt6/W9ut8HCIJCbr9owTtj9ZiP5YKB' +
  'o4fhNIcyiHN4Ru6Hl/EojjxupcMoFxFWb412/SOuHBFQ1k4kprZchqYYnt4MwMhru2utW5H9P3WhO4vzJqv3ViwYPrU6' +
  'FdqDm6gSTzfeDksdcUN5hDGjgU9t0xukUt5l6EozMr6QcxpNEUBsi6jTkWcOBktV4Lgfv9Fp9YwyEjbyH1wkuVD5KnW6' +
  'XTGVu/oJmxOb/6v5urEa85LUnDHKr8/y/q+jwDeOA6Px02diMGjtamq7T92RvgW/URLvuSwneDxXe8pXt8SoaYPhCv+X' +
  'rMqsA6+a0G0oZ67eHslXQPbMtajEIGEUeKQNTYsukOaOE6Yz6qyprRpXIA4Mn5a1ud524vYm+f8At9PSqYRzI+H7YHKd' +
  'R/vysP8P/WNPZOHJAbk9C4qBHvakfnDoL+X467HAPa8itHfGgVn/9OyI3cyEfTPTdn6n9GkWbv1HlDKElvndcQs3ox3C' +
  'q2QmlVl6wTvrFQM+2H5tfwryE+hN1rnhYMB8dVwVvVucgUiTvLnopOjHFZH+vzn5krrd7FrIaHIhi1Yw1o1X19I/wkYi' +
  'SmE98Dg4DxdXpaf2K2OHqrrxZzXW+Pi1xUZKN0ShDpxqAUVcJWrcJR8Rv9qrOWMxNgi4/hg4KFUk7ehzLFSnDKDqQ8zv' +
  'ufOGhb9DWaP/6lhNTwUlQchSj/UboXpRg7BGxocf3FXbGFcwY1RsckOFzSod18uU36szOOXhR5utwJkTSzQlV9alqVM4' +
  '/MIBE/VmWkbD9LHtwcjXGPXLSorJ5BG6tOn9cBW0O4aLpxxB+VnQR5an4PHPSEYpcN0xiVWpDm1NHk5Jfa4a0VUi9FyL' +
  '857X+h0FGwr3tNutjSKyX6Zgz15iT6B0qWsshaVGjXV37tFYSXk+AfCfwqpyEseI/S7233Bq00zL+9FM7H8s1oLrbgsL' +
  'yLIKL1QC6hA+rtFJCgFpQtq+5YfNOatvOyct0uqihge4dGMs8NeMsQ227CY3eU9zEWNRGBZ+GCEGugMRfqg6VY0hMXM6' +
  'Zvim2rVia/rT7z4GvcUEv1s/0wUF9wrogA8DZypH1KmlHSTjZ5+jwdA5P1hlX6rMWvy+NWGemUTI7/skHUjzlDcEbrJI' +
  'eS2fKIi5Wr3mnjSfk1kHsD7499QlXPa7v2UE5SPf6o7njpSJxlVDwydLKUQuEN/Fm0zmf24K/NjH0eTpZaSNbMKenLeT' +
  'LCWYLBTivA+sONV8GwOKIuDb442JHtclC1prPEIw0XTJ9GSUp+JzxUc4IAwMSp6/Lqoq/eWnhiAvvCvn1hDi1FHKLhCw' +
  'pOBgzLjydGBf7nohi8fkB6p6//QFFj2KWldA1omjKq4De+BXzShQGzYgMe9JAiGZeEqdjFjWiWwE8sYDQBNZyi4343xb' +
  '+kH2yOA1vPrFkhPvuR1b1QdF3rV6pZXIzTyLOau/0IGdyi6dX2MbvDJSJR7uYdvbpFfGpIBBpkzK31LB43jjb7s7z75V' +
  '4cJV1sSG2c7NL2eM5kdXuH67lnKeXH0x1Hp5cv/j7G9aQl6LabbmwlkSwWXTYAH6VFrPvUGIL/KzndOWU4mBVazEzrGS' +
  'EmrLK4uag3r/HOSG5N+lY+zO+cnrOeIxHBYRcfJNUkuqiD1zxTAPHOdo6ijJuVuDZ4NT5qZ0Jky1Z0gHnAF1nqjgRm4J' +
  'fnM9E30olnX7N0Jekal+ltmFQuRmzxXyxBoUzsneDYyenmzFDpLXclFHNYUEC6Iw3R9GN8yw10zL9sL2An02fZpZL4tA' +
  'PlxzbzfOPn8msklKM/pzKVrMdrtMdz0EyN6llWBjs9X942A5fQxhokr8CD+OFCLab2mkSfZcU4yCfDj4ILEFW96Wyf5o' +
  'ZuB9TvN9jn+7Z+bxuS7oAcBXGdg6wd2XRvO1YY6aZGjX7qN+obtghR1HJ93yfsimte+9hv/oUFgk/Ibue6iJo3zbTGfU' +
  'jfYPIFWvyXpqAUaaudreeMMzNZS1xjXLOFjtIhraR2/m4UkwDc1gdb5LRqZPYXicEr1YW3XRFzAEWqfIJf2epgUp08og' +
  'AXrjNe2TRzuzRqMUrcDdCdH3KRmQjl0RxX+B0i2jiUW4Or3D1sCLZ8Pzl/vmMajGxTsEFOfP0+SDI0uf8bEUoGISMvtJ' +
  's304rW6LTex/HEhVotlztfDdAudRQvBmgtfWN2JU3rVDbkzp0RXQSWSj2RpNXB4q9Y6ZrUXVQh4wElFkEfgynh7EcM3Q' +
  '26S5d1Q2c9Rm2o95J+YQI4iP7yvXTu6lwknmlyNaG1h4eMHEd50+/Pchs+5tFqq+HxgPg0GCThNWSKW474Le31+uHpt4' +
  'sp5ug9uCPSym1slrWbkln/ElAsOR6YGvvv70aYpDQBjAxEff/ws45reJABnCDDoGNdpot7cUZVOFyRsSnNsygJYn2noC' +
  'LQaXrEfJcQ7NHxWri4QwMXmf6esvLms6POX57AHslZYy8CS9wGmRi5TjUrNX9dinE+E3jBCSlD7XHjC2aeVBuv0YJDOj' +
  'Isy9j0wkoBVbpgHt5OsLqQ/Sh8qef8arZwEchqWABEK6Hc46KbXXIqbiOeh3CSRytzQjoG4WC4sc2QJJ5nbzS+LkXCLZ' +
  '3oj3X2txDKL5Y5al3nxBB/hJXUzcS+odiyM1XHCfiYZ9NxnB1MByXVOoS3Zc1+E87eNrFcbGNzR9dO/Hw/hupxTRmx2J' +
  '+PZD1M50ZgZgidKM2ZMJyZ6SQw2hXRsCBlulzIGh2bqvSF2ZMDR1oH9B0BQsgFUcb/ozARVc7lt/JYP1j7UprNH+3n3/' +
  'CYiFNQXyVk6d7OQSm9XSLWCkn+b1aGgB1wF+Q5tRa4CLBtxjD1YRtD7H0/FfXWgKqu0Ph4a+cg7vPv0LnbYESLGozw+Z' +
  'NDFmICuliWEinmVjnR61p9U2GjK/lvDZ6AcTFhJs9eDD+A9okGISoeaQlDCZ4WJfkAt3uooAks2x5R7gNkpZ1KTcxU8s' +
  'lEWlrb7t86HoVRsVeSEtRIeG6bS725JTNp0rwi1MWJjUsS4J6mwU1ORrFHZgAjI+ulkOf6ticPrACoW3xLmEk1YMI7eD' +
  'kKBfqOGRj8hXLvPRoryT6BIFmXXaFESeY+OeZqf7b52gJNeAAZy5Ihamh1L24DbNRJlm+o3au4pLmVXJZJJglYErmBNH' +
  '6Xh1eMfuw4TX1ypy1zN1vIhneLDQdEltbyICifqn59o0/nG2SEj6WcFqIlhVitljVih3CyonTvadCHC4M4Nso4daesF8' +
  'tHuTY+TgW1gr8xwKtuN+3EDrBVZT/VPdsX6m31tEXltT+VDSZp15bTLNEXEslakzVDX1lvzaAs29wtWRtRxdccNgzvJ7' +
  '5gYm+x/0ZLf6rwDIo2MJ8ZtKHpt/hHT/Kgfrnh7rNBkvlYOLrG2mOw/HHjUpuYHdoE6QvscYIOrDQ8XejMf3XCDxTzTZ' +
  'MFFgXSs3A6mQiYWRLMrXfk63qU7ili/0dZNjkb2XiaRbijY8BsadcDb+b59Bk+T6numhjmG22cHPii9MsBfxQNj+ej1k' +
  'syo/64/TVBbPmGiE7DnZyiQL3uAIUvt5Pn95uifGHd4mIJiIomvDQ5jG0yWaMtEJtnaL3A4/oGV4YE3cBiqaDA4zjxsH' +
  '3a8Oj77N0evrRo19SaWaEdLP+wiiPNsVlOwyWIzoRRkB6+yGfbE6vR45sbjsB/Yvr9MMKcWsLqGrh720rc7fDRHVleL8' +
  '++bM2gCuqjf4rHPDS/3mFwrL8we/M0ytB1xiZtvnjI+soOmhXIAGAYblpXvoyURmLJO4VFqnqjCFLD3y4zJEHgPdZQdk' +
  'XG4gnW/lQP9moQMTfGcdFafZ9apD9eAlctDkL9baJABvaLgH8se76mTfa4eMl0GYEHZOyEIODoxuin57ytYp0Yfnya1i' +
  'OzZ/p8FVqrAIG1YtNG8sFfF0MA2vPWdBgUNWDZE5iJbjE1KD52JkVILkJEZZTTWOadd5kWXAKUa0ZpyDvbkI7wYfOit2' +
  'amDt4k3YugViDcM/cEK8QKUUWSc0kTssnwT9d3JOq6bpSpDfuRXsSDwG3Uz8zEuDLM0bz/ZCFVnb8vkAQe/oE3ZaEVQL' +
  'bgGftfWIAASb/5B5zdu8K7FvvOQWCaw8CrtMcHViz4sTdlqU47KF3mpOyV8IyVuhxwHR+DCDLErRHNTcX4tM0JLlIlCI' +
  'SbtFdCv9ZXWZLpxUt3vEH5t70H47/2sPYVT23pnzT8V80pTmTvqWzMWQHCP14xetSxP5IjHNpZSf990DMgiby8Vp0Uyk' +
  '4rN9oLNoDBj+6X3wh9FDhoYRyx1fvGRGyB18HKeuV87RbNrBTqhryAs1KIos9qj2toACcH2jifM/PATbjZ5fq+t9G6W6' +
  'jTwnsM1VkRc+2OyfrB4gZqoj+CWeX3KfA36uS2DM7+rxdefmPbUPRtijXdUAplw4s6gJaD0wOJYdbb9OII55OVDY6fmZ' +
  'RwFHsiBwPj9xrj9Z5saVdgqomv/2cFBVmEml+4/fWuxfib+dA/oWRjA1ohLu4POHCUr7qdBKj4ovCDzDZ2f50qYZCk47' +
  '1MO7IgrWVzxg1cgjxwat8HTBy1DiZQ7e1J/JzgwQE9KK0cBwLC2OfV0V6WgUhrSdDWQ1sm4HISUTNbxoR90TRaoc0pyp' +
  'nkqET34I7TD1XieQJhzwzGdtgu4KIDo25d0L4jogKd7n/srcsqbtfrOisuXYbJnZqHTVdMrHdL7WN+0DMrYfdVkTjE17' +
  'PsF/6g/78CO4sutB4DPA177jXLRwTV3tcMp5uf3pp8qcyA2SdXVeXjc7POIPX4fIgtvWVB3xDv8bDP9UzPrUJGhQFJLL' +
  'OWXU1HgPcEPd9tIVIHyt74DN6eyimZMv7IR3ZqXy3uQhvcG+JtfnTvN0U8iMu7a23mhJZkmzWb+/2QVt4xiVnF4zgD6r' +
  '32J2X9rhiSwvjSVfVVeLV/+Q79AZv7dvrxHGWAaTmnaDP343NnNpbqf+S81hXIOqpsduQgrlOpUwfxKgGpkkumVFzHcJ' +
  '9tlYxJiW9O4Rtcw3SmvuknakGg+KD93uVQoQhypz0y9qw6oJSnIyuiW+gbn7ihqpnknqgZ1axDXnB8627TJpbagQkdXz' +
  'f0mqXIa9GXFRvknrcECgSDgLHlOnr9ksqcvcFuQFuMxp0rG9+dRVnuCexQNwisweJX2CZRA58fP1LExcE+CgOzlkm6so' +
  'R3VrXV+aHzzpXi5vqKaoCvUj0ZQOY01g4hj4qLD3hMZKM/8/w7b5lwF5d0YAAAAASUVORK5CYII='
